### ISSUE TITLE
Error 500 when trying to select a product

### ISSUE THREAD

**Issue by marionf** [PrestaShop/ps_buybuttonlite#2]
@Joukz 

When I try to select a product, I have a 500 error

![capture d ecran_339](https://user-images.githubusercontent.com/13449658/46090295-b6cb9400-c1b0-11e8-87ae-862b6a50dce9.png)

**Comment by Joukz** [comment]
It should be solved now. Can you check it? :)

**Comment by marionf** [comment]
Fixed by #3
