### ISSUE TITLE
Can order a customizable product without complete required fields

### ISSUE THREAD

**Issue by marionf** [PrestaShop/ps_buybuttonlite#5]
@Joukz 
If I select a customizable product that has at least one required field, an alert should be displayed in the module
Because the product is added to the cart and the order can be completed without the required field completed
Ask to Alex.D for the message

**Comment by Darmona** [comment]
Has been solved with an info message "You should share the product page link instead" if customizable product selected.

**Comment by marionf** [comment]
Ficed by #3
